---
- name: Create Security group
  ec2_group:
    name: "{{ sg_name | default('my_sg') }}"
    description: "{{ sg_description | default('My Security Group') }}"
    state: "{{ sg_state | default('present') }}"
    region: "{{ sg_region | default('ap-southeast-2') }}"
    rules: "{{ sg_rules | default(none) }}"
    rules_egress: "{{ sg_rules_egress | default(none) }}"
    aws_access_key: "{{ sg_aws_access_key | default(none) }}"
    aws_secret_key: "{{ sg_aws_secret_key | default(none) }}"
    ec2_url: "{{ sg_ec2_url | default(none) }}"
    profile: "{{ sg_profile | default(none) }}"
    purge_rules: "{{ sg_purge_rules | default(true) }}"
    purge_rules_egress: "{{ sg_purge_rules_egress | default(true) }}"
    security_token: "{{ sg_security_token | default(none) }}"
    validate_certs: "{{ sg_validate_certs | default(true) }}"
    vpc_id: "{{ sg_vpc_id | default(none) }}"
  register: sg_info
